"""Expense

Revision ID: 86ebc20325d2
Revises: 
Create Date: 2020-08-30 11:21:47.191336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ebc20325d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=120), nullable=True),
    sa.Column('occurence', sa.String(length=128), nullable=True),
    sa.Column('expenseDate', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_expense'), 'expense', ['expense'], unique=False)
    op.create_index(op.f('ix_expense_price'), 'expense', ['price'], unique=False)
    op.create_index(op.f('ix_expense_timestamp'), 'expense', ['timestamp'], unique=False)
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=120), nullable=True),
    sa.Column('occurence', sa.String(length=128), nullable=True),
    sa.Column('payday', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_income'), 'income', ['income'], unique=False)
    op.create_index(op.f('ix_income_payday'), 'income', ['payday'], unique=False)
    op.create_index(op.f('ix_income_price'), 'income', ['price'], unique=False)
    op.create_index(op.f('ix_income_timestamp'), 'income', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_income_timestamp'), table_name='income')
    op.drop_index(op.f('ix_income_price'), table_name='income')
    op.drop_index(op.f('ix_income_payday'), table_name='income')
    op.drop_index(op.f('ix_income_income'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_expense_timestamp'), table_name='expense')
    op.drop_index(op.f('ix_expense_price'), table_name='expense')
    op.drop_index(op.f('ix_expense_expense'), table_name='expense')
    op.drop_table('expense')
    # ### end Alembic commands ###
